version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - OMDB_API_KEY=${OMDB_API_KEY}
    restart: always
    volumes:
      - ./thesite:/thesite
    depends_on:
      - migration
  migration:
    build: .
    environment:
      - SECRET_KEY=${SECRET_KEY}
    command: python manage.py migrate --noinput

